### ISSUE TITLE
Feature request: access history

### ISSUE THREAD

**Issue by cands** [yohasebe/fzf-alfred-workflow#2]
Thanks a lot for making this most useful workflow!

I wonder if it would be possible to add a function to access previous search strings (e.g. by pressing arrow up). I find I often want to repeat previous searches (maybe slightly modified), so such a feature would speed up the process.

**Comment by yohasebe** [comment]
Thank you for using fzf-alfred-workflow and for your suggestion. In the latest version, 1.5.0, I have added a feature to save search history. Please check the README for more details. 

The latest version is already available on GitHub. However, if you have installed the program from Alfred Gallery, please wait until the latest version is registered.

Thanks!

**Comment by cands** [comment]
Thanks a lot for implementing this! This feature is very powerful.
