### ISSUE TITLE
iCloud

### ISSUE THREAD

**Issue by notDavid** [yohasebe/fzf-alfred-workflow#5]
Hi there,

i can't seem to succesfully add my iCloud drive folder, it's not finding any results. I've set the path to: 

`~; ~/Library/Mobile Documents/com~apple~CloudDocs`

Not getting any errors either, checked the "Alfred debug log" too.
Any idea what might be happening?

Thank you!

**Comment by yohasebe** [comment]
Sorry for not getting back to you sooner. I tested the exact settings myself and can confirm that it works as expected in my environment. I was able to locate all files and folders under `~` and `~/Library/Mobile Documents/com~apple~CloudDocs`, except for invisible (dot) files/folders.

The issue may be related to some iCloud configuration settings. I will update you if I find any further information.
