### ISSUE TITLE
Not showing any results

### ISSUE THREAD

**Issue by mgussekloo** [yohasebe/fzf-alfred-workflow#6]
Hi, thanks for this workflow! I've installed from the gallery and followed the instructions, but it's not showing any results (no matter what I type, it says "No results found". How should I debug this?

**Comment by mgussekloo** [comment]
For future reference; I need to resolve dependencies from the Alfred Gallery. Maybe it would be useful if the workflow could return an error if the dependencies were missing?

For now, I'll close the issue, sorry to bother you.

**Comment by yohasebe** [comment]
Thank you for your report! I will include a dependency check in the next version.
